# Uncomment the next line to define a global platform for your project

platform :ios, ‘8.0’
use_frameworks!

target 'MovieViewer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for MovieViewer

  pod ‘AFNetworking’, ‘~> 2.6’
  pod ‘MBProgressHUD’

end
